### ISSUE TITLE
Make navbar mobile-friendly

### ISSUE THREAD

**Issue by tgoins** [NatsukiBot/web#1]

**Comment by tgoins** [comment]
Completed. Nav is now responsive, and looks decent on mobile.

**Comment by brandonbothell** [comment]
Doesn't work well on my phone. Login button is cut off.
![lol](https://i.imgur.com/pQrKBEd_d.jpg?maxwidth=640&shape=thumb&fidelity=medium)

**Comment by tgoins** [comment]
Get a bigger phone.

**Comment by brandonbothell** [comment]
Thanks for the advice
